### ISSUE TITLE
Implement safety checks

### ISSUE THREAD

**Issue by maxbalves** [maxbalves/PostBy#28]
At the moment, the timeline and details page are refreshed every time the view appears again on the screen.
Problems:
- This can be frustrating for the user in case a post they were looking at is moved around because the homepage refreshed
- This can create an unnecessary amount of requests to the Database and eventually exhaust the free plan quota.
In addition, it's possible that users access posts that have been deleted. There needs to be a check if a user tries to access such a post.
**TODO:** 
- [x] Home Page viewDidAppear will only reload data for table view (not call Parse).
- [x] Accessing delete post from home or details page refresh, causes the user to leave the details page and removes the post from timeline
- [x] Accessing a deleted post from map screen causes the user to leave the details page and removes pin from map
- [x] After liking a post in details page, the home page will reload the data and show the like/dislike without needing to query parse
- [x] Like / Dislike safety checks
- [x] Test!
