### ISSUE TITLE
Fix Deletion Functions due to Relation Problems

### ISSUE THREAD

**Issue by maxbalves** [maxbalves/PostBy#45]
When an object is deleted, all relations to it are not automatically deleted. Parse leaves behind a hidden file.
The problem is that when querying object `A`'s relation, if object `B` was deleted but used to be related, it will secretly count this deleted object as part of the query. This causes the query to return less results than intended due to the deleted objects taking up space.
**TODO:**
- [x] Create workaround of querying 1000 objects limit. Perhaps recursion or loop, using `skip` property
- [x] Implement `deletePost` and `deleteComment` function in CloudCode
- [x] Fix CloudCode deletion functions to also manually remove relations. Try to reuse `deletePost` and `deleteComment`
- [x] Create reusable `deletePost` and `deleteComment` functions
- [x] Fix CloudCode for `removeOldPosts` job in order to manually delete relations too
